### ISSUE TITLE
Update of PAGE-XML documentation

### ISSUE THREAD

**Issue by cneud** [OCR-D/ocrd-website#107]
The current [documentation for PAGE-XML](https://ocr-d.de/en/gt-guidelines/trans/trPage) is still based on the [2018-07-15](https://www.primaresearch.org/schema/PAGE/gts/pagecontent/2018-07-15/) PAGE-XML schema. Meanwhile PAGE-XML [2019-07-15](https://www.primaresearch.org/schema/PAGE/gts/pagecontent/2019-07-15/) is current, with a next version 2020-07-15 coming soon.

Is it possible to automatically re-generate the documentation for a new PAGE-XML schema version?

**Comment by kba** [comment]
The schema docs are generated with oXygen, which I don't have installed unfortunately. @tboenig Can you regenerate and document how to do that in the README?
