### ISSUE TITLE
workflows: mention new ocrd_wrap and ocrd_segment processors

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd-website#115]
In addition to #104 IMHO the following **new processors** should at least be mentioned (if not recommended) in the workflow guide:

- `ocrd-preprocess-image` along with potential / example tools (replacing `ocrd-olena-binarize`, replacing `ocrd-im6convert`, simulating `textcleaner` and other IM scripts)
- `ocrd-skimage-normalize`
- `ocrd-skimage-denoise-raw`
- `ocrd-skimage-binarize`
- `ocrd-skimage-denoise`
- `ocrd-segment-replace-original` (to re-base PAGE coordinates to "new original")

**Comment by EEngl52** [comment]
solved by https://github.com/OCR-D/ocrd-website/pull/121
