### ISSUE TITLE
best practices / setup.py

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd-website#118]
From: https://github.com/OCR-D/ocrd-website/pull/117#discussion_r450355546

> Maybe already point to:
> 
> * reference external `requirements.txt` file (and how to initialize one via `pip freeze`)
> * reference README.md for `long_description`
> * reference version from version in external `ocrd-tool.json`
> * CLI naming conventions for `entry_points/console_scripts`

> * set `long_description_content_type` to `text/markdown`

**Comment by bertsky** [comment]
Plus the remaining items from our old [checklist](https://hackmd.io/g-8QuOAnSQeqnb8PRNjFbQ)

**Comment by bertsky** [comment]
> Plus the remaining items from our old [checklist](https://hackmd.io/g-8QuOAnSQeqnb8PRNjFbQ)

ok, so there's a separate issue for that now: #119
