### ISSUE TITLE
models / instructions for mounting models into docker container

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd-website#120]
c.f. https://gitter.im/OCR-D/Lobby?at=5f0485b8a9378637e8b212c2

**Comment by bertsky** [comment]
Covered by https://ocr-d.de/en/models#models-and-docker already?

**Comment by kba** [comment]
Yes, this has been documented. There is still the issue with permissions https://github.com/OCR-D/ocrd_all/issues/252 though which we can track there.
