### ISSUE TITLE
dead link to mets example in user guide

### ISSUE THREAD

**Issue by JensHeinrich** [OCR-D/ocrd-website#126]
The [user_guide](https://ocr-d.de/en/user_guide#non-existing-mets) links to an 404 `https://ocr-d.de/en/example_mets.md` as example mets.xml

**Comment by kba** [comment]
The example here is https://github.com/OCR-D/assets/blob/master/data/SBB0000F29300010000/data/mets.xml But I am not  even sure whether that is a good example anymore, maybe this would be a good moment to replace it. @EEngl52 @bertsky Any proposals for "the archetypical OCR-D METS file"?

**Comment by EEngl52** [comment]
what about this one? https://digital.staatsbibliothek-berlin.de/werkansicht?PPN=PPN895878739&PHYSID=PHYS_0005&view=overview-info
