### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by mnoelte** [OCR-D/ocrd-website#139]
On https://ocr-d.de/en/user_guide the link "this example" (METS example) leads to https://ocr-d.de/en/example_mets.md resulting in an 404 error (this is my first issue in ocr-d; pleas tell me if I did something wrong)

**Comment by kba** [comment]
> (this is my first issue in ocr-d; pleas tell me if I did something wrong)

:tada: Thank you, nothing wrong, except that it has already [been reported](https://github.com/OCR-D/ocrd-website/issues/126) but thanks for the reminder, we really need to fix this.
