### ISSUE TITLE
Wrong formatting of the examples in the API docs

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd-website#179]
![image](https://user-images.githubusercontent.com/34309482/96154862-8da10c00-0f0f-11eb-8dc3-3c5b285f00b0.png)

I think this should be formatted as a code block? https://ocr-d.de/core/api/ocrd/ocrd.workspace.html, under both  "Example" headlines.

**Comment by bertsky** [comment]
Hard to say what syntax exactly our [rST dialect](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) expects here. Maybe we are just [missing 4 characters of extra indentation](https://github.com/OCR-D/core/blob/b07ff2b2fb2f540f6c89cfdd1bbdbfc06224d8fc/ocrd/ocrd/workspace.py#L522-L527)?
