### ISSUE TITLE
RSS-Feed for blog

### ISSUE THREAD

**Issue by darkdragon-001** [OCR-D/ocrd-website#186]
Please add [RSS support (XML representation)](https://en.wikipedia.org/wiki/RSS) to your blog such that everyone can follow this awesome project anonymously with their favorite feed reader.

**Comment by kba** [comment]
There is an Atom feed at https://ocr-d.de/feed.xml that I forgot to link to in the templates.

**Comment by darkdragon-001** [comment]
Thanks a lot! Stay awesome!
