### ISSUE TITLE
document CUDA installation

### ISSUE THREAD

**Issue by EEngl52** [OCR-D/ocrd-website#187]
document required version of CUDA and installation in setup guide

**Comment by cneud** [comment]
There is now a guide available in the wiki: https://github.com/OCR-D/ocrd-website/wiki/Setup-native-CUDA-Toolkit-for-Qurator-tools-on-Ubuntu-18.04

**Comment by kba** [comment]
Maybe we should link from the setup guide though, in case someone `ctrl-f`s CUDA on https://ocr-d.de/en/setup?

**Comment by cneud** [comment]
The only issue I have with that is that this (native) CUDA environment installation is specific for the Qurator Tools and therefore I am unsure where that would fit in the setup guide (rather than confuse e.g. users of Docker, ocrd_all)?

**Comment by bertsky** [comment]
> The only issue I have with that is that this (native) CUDA environment installation is specific for the Qurator Tools and therefore I am unsure where that would fit in the setup guide (rather than confuse e.g. users of Docker, ocrd_all)?

IMHO your wiki page is sufficiently general to cover the case of ocrd_all native installation with CUDA support. As the setup guide (or the ocrd_all README) currently does not mention the GPU / CUDA option at all, we need to come up with a way to present this anyway.

I would say a good place to discuss CUDA options would be _after_ explaining the 4 options in detail and how to test them, right before the installation of the research data repo. The new section could be divided into a Docker and a non-Docker subsection, linking to the main install options and adding specific CUDA instructions. In that context, the Qurator CUDA instructions could serve as a cross-reference after linking to the general Nvidia instructions for various platforms.

**Comment by cneud** [comment]
Actually this reminds me that for a future overhaul of the setup guide, I think we should separate the instructions for the 4 installation options (and imo drop what is currently [4]), leading most **users** who do not want to make code contributions towards the Docker path.

**Comment by bertsky** [comment]
(Agree on dropping 4...) but I don't think we should split the guide (if that's what you mean) – this should be a single unique source. We already distinguish (in the text body) quite clearly between recommended (Docker ocrd/all), neutral (native ocrd_all) and not-recommended (native single-repo). But we could improve the hierarchical structure of the guide (with section numbers and a better TOC).

I don't think this is about the distinction users-developers at all. We've seen how even in the Docker option it's very useful to include repos to be able to deploy hot-fixes painlessly and get precise version info from bug reports.
