### ISSUE TITLE
kwalitee einbinden

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd-website#21]
vgl. insbesondere https://github.com/kba/ocrd-kwalitee/issues/2

**Comment by bertsky** [comment]
ping @kba 

(also, adding ocrd_eval.md to the spec page)

**Comment by kba** [comment]
I've updated the spec in the website now, including ocrd_eval, should be visible in a few minutes.

kwalitee has been replaced by QUIVER, and it's available at https://ocr-d.de/quiver-frontend (independent of the ocrd-website repo, it's using the GH pages of https://github.com/OCR-D/quiver-frontend itself)
