### ISSUE TITLE
GT guidelines: fix formatting

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd-website#225]
I feel like I have reported this issue already, but cannot find it anywhere (here, in `assets` or in archived `docs`):

The GT transcription guidelines often contain tables of characters, with an image and a text transcription. The latter then often contains HTML escape codes which render verbatim instead of being displayed as special symbols.

AFAICS this is because the pages (whereever their original format may be) use `code class="ph codeph"` elements for them. These should all be replaced with simple paragraphs (perhaps using monospace fonts).

Example: https://ocr-d.de/en/gt-guidelines/trans/tr_nasal_level_2.html

**Comment by tboenig** [comment]
At first:
-  the documentation has a main convention:
see: https://ocr-d.de/en/gt-guidelines/trans/trDokuKonventionen.html or in German https://ocr-d.de/de/gt-guidelines/trans/trDokuKonventionen.html

I cite the DITA documentation from https://www.oxygenxml.com/dita/1.3/specs/, I would also have DITA documentation from http://docs.oasis-open.org/dita/dita/v1.3/.

First:
the text, that you transcribe for ground truth, represent the example. In DITA-language have you at least two options.
1. a formal (example: <tt>[https://www.oxygenxml.com/dita/1.3/specs/langRef/base/tt.html]) or
2. a semantically (example: <codeph> [https://www.oxygenxml.com/dita/1.3/specs/langRef/technicalContent/codeph.html#codeph__example])

We decided in the documentation for the semantically option.
We know, that <codeph> an element the programming element group is. Ground Truth are not a programming language but in a kind of figurative sense.

Second:
HTML has limited possibilities for representation of semantics. The HTML is a result of automatic transformation. If you found a error, the error will be corrected in the DITA source, not in HTML.

**Comment by bertsky** [comment]
(Edited your comment for correct hyperlinks of tt and codeph. The syntax is `[link text](link URL)` BTW.)

**Comment by bertsky** [comment]
> At first:
> 
> * the documentation has a main convention:
>   see: https://ocr-d.de/en/gt-guidelines/trans/trDokuKonventionen.html or in German https://ocr-d.de/de/gt-guidelines/trans/trDokuKonventionen.html

I _did_ see this exception and in my [pull request](https://github.com/OCR-D/gt-guidelines/pull/20) took extra care not to replace such usage.

> First, the text, that you transcribe for ground truth, represent the example. In DITA-language have you at least two options.
> 
> 1. a formal (example: [tt](https://www.oxygenxml.com/dita/1.3/specs/langRef/base/tt.html)) or
> 2. a semantically (example: [codeph](https://www.oxygenxml.com/dita/1.3/specs/langRef/technicalContent/codeph.html#codeph__example))
> 
> We decided in the documentation for the semantically option.
> We know, that an element the programming element group is. Ground Truth are not a programming language but in a kind of figurative sense.

I see. I understand your reasoning, but in this case, what's of most practical importance is how these markup decisions **look like** (get rendered). And there simply nothing worse than making your examples unintelligable because no-one can actually see the glyphs (or copy them to clipboard) you want the images represented with.

So I would recommend either:
- revising that decision (could be replaced automatically, one) – or
- sticking to it, but doing some postprocessing each time (like the commands documented in my PR)


> Second:
> HTML has limited possibilities for representation of semantics. The HTML is a result of automatic transformation. If you found a error, the error will be corrected in the DITA source, not in HTML.

Exactly. That's why I was asking for a fix in the sources, not the output.

**Comment by bertsky** [comment]
Thanks @tboenig!
