### ISSUE TITLE
idea: use docker interactive shell instead of wrapping everything in docker calls

### ISSUE THREAD

**Issue by twerkmeister** [OCR-D/ocrd-website#247]
When I just tried out a bunch of things from the user guide I found myself very intimidated by the long docker commands. So what I did is just start an interactive session using 

`docker run -u 0 -v $PWD:/data -it -w /data -- ocrd/all:maximum /bin/bash`

and then just using the normal commands from there. This also allows for downloading of models with the resource mgr, stopping and restarting the container.
`ctrl-d` to detach/stop container
`docker restart <container id>` to start container again
`docker attach <container id>` to get back into a shell on the container

Will probably be my goto workflow going forward. Might be worth considering for the tutorial as well!

### potential improvements
* might be better to use a non-root user, but my real user id wasn't available inside the container and then I couldn't download models due to missing permissions to create directories
* naming the container

**Comment by bertsky** [comment]
[is what I'm sayin all along](https://github.com/OCR-D/ocrd-website/issues/98) :grin:
