### ISSUE TITLE
ocrd-eynollah-segment ... ... -P models default

### ISSUE THREAD

**Issue by jbarth-ubhd** [OCR-D/ocrd-website#327]
Dear reader,
docs says `ocrd-eynollah-segment -I OCR-D-IMG -O OCR-D-SEG -P models default`, but eynollah complains about excess parameter `default`.

**Comment by kba** [comment]
Can you share the error message - are you sure you used `-P` (capital P) not `-p` (lowercase p)?

**Comment by jbarth-ubhd** [comment]
Oh, sorry. My fault. Did `-P models /path/to default`.
