### ISSUE TITLE
Table not working

### ISSUE THREAD

**Issue by lena-hinrichsen** [OCR-D/ocrd-website#347]
I stumbled upon this table not working anymore in https://ocr-d.de/en/setup#ocrd_all-via-docker (at the bottom of this screenshot):

![table](https://user-images.githubusercontent.com/86944988/229840058-ea111dce-c16a-472a-b1ef-5e557b28f848.JPG)

**Comment by kba** [comment]
Looks like Markdown is not rendered within `<details>` anymore :/

**Comment by lena-hinrichsen** [comment]
Shall we try setting `parse_block_html: true` under `kramdown`  in `site/_config.yml` ?
(https://stackoverflow.com/a/27897223)

**Comment by lena-hinrichsen** [comment]
> Shall we try setting `parse_block_html: true` under `kramdown` in `site/_config.yml` ? (https://stackoverflow.com/a/27897223 and https://kramdown.gettalong.org/syntax.html#html-blocks)

after testing that out today, that was a bad idea, apparently (didn't manage to test yesterday) :)
This works for me: https://github.com/OCR-D/ocrd-website/pull/350

**Comment by kba** [comment]
> after testing that out today, that was a bad idea, apparently (didn't manage to test yesterday) :)

It is the right idea, and the same solution, if you set `markdown="1"` attribute that is the same as a locally-scoped `parse_block_html: true`. But it does not seem to work correctly  with both mechanisms, cf. #350
