### ISSUE TITLE
docker test .zip not found

### ISSUE THREAD

**Issue by jbarth-ubhd** [OCR-D/ocrd-website#364]
`wget "https://ola-hd.ocr-d.de/api/export?id=21.T11998/0000-001C-F82E-8&internalId=false" -O wundt_grundriss_1896.ocrd.zip` 

does not work:
`404: Not Found.`.

**Comment by kba** [comment]
Thanks for the report, sorry for the late reply, has since been fixed in https://github.com/OCR-D/ocrd-website/pull/368 - this should be the last time that any OLA-HD links break, the ones we're referencing now should be stable indefinitely.
