### ISSUE TITLE
OLA-HD links on setup guide are broken

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd-website#366]
In https://github.com/OCR-D/ocrd-website/blob/master/site/en/setup.md, we link to

https://ola-hd.ocr-d.de/api/export?id=21.T11998/0000-001C-F82E-8&internalId=false

but we should link to

https://ola-hd.ocr-d.de/search-detail?id=21.11156/BFBAD520-65F4-430A-B4B2-C81A296C9E09

@tdoan2010 Any idea how this can happen? Shouldn't the handles be persistent for ever?

(ht @michalbubula)

**Comment by tdoan2010** [comment]
As explained by Jonas, they switched from test PIDs to production PIDs. That causes the problem.
