### ISSUE TITLE
Link for the OCR-D models is broken

### ISSUE THREAD

**Issue by michalbubula** [OCR-D/ocrd-website#369]
In [https://ocr-d.de/en/models](https://ocr-d.de/en/models) there is a broken link for the list of the file resources that OCR-D/core is aware of:

[https://github.com/OCR-D/core/blob/master/ocrd/ocrd/resource_list.yml](https://github.com/OCR-D/core/blob/master/ocrd/ocrd/resource_list.yml)

**Comment by kba** [comment]
Oh, right, the location changed after we moved to a single `src` dir. Thanks for spotting.
