### ISSUE TITLE
workflows: fix recommendations

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd-website#90]
~~The HTML-based tables seem to break the table of contents and headings all over the page. I recommend switching to pure Markdown tables. These can be easily input in Emacs' table editing mode (the format which Markdown adopted). Just copy & paste the existing tables rendered by a web browser and do `M-x table-recognize` ...~~

Apart from that, the workflow _recommendations_ are still wrong:
- `ocrd-cis-ocropy-segment` on page level
- `ocrd-anybaseocr-deskew` instead of `ocrd-cis-ocropy-deskew`
- `ocrd-cis-ocropy-resegment` after `ocrd-cis-ocropy-segment`

**Comment by EEngl52** [comment]
@bertsky I just forgot two end tags in the first table, this is why everything looked weird... 

@VolkerHartmann tested the processors again, following the new workflow. Based on that we will prepare new recommendations soon.

**Comment by EEngl52** [comment]
I just updated the website with the new workflow recommendations

**Comment by bertsky** [comment]
Thanks!
