### ISSUE TITLE
presentations: add workflow slides from dev ws

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd-website#93]
I don't know whether this is the right place, and I am turned off by all the raw XML in the Markdown file, so here is the issue:

Can we add the following presentation slides:
- Robert Sachunsky, Kay-Michael Würzner : _Flexible OCR workflows with OCR-D_ 
  https://hackmd.io/@FKFH0M1sR2SdJZwK5U8Cfg/S1YQ4NeNr#/
(from the 3rd OCR-D developer workshop on Aug 26 2019)

**Comment by bertsky** [comment]
[Flexible OCR workflows with OCR-D.print.pdf](https://github.com/OCR-D/ocrd-website/files/4558346/Flexible.OCR.workflows.with.OCR-D.print.pdf)

**Comment by EEngl52** [comment]
We didn't include any presentations from the dev ws, as they are mostly work in progress. But if you want us to, we will include it of course. I guess @wrznr would be fine with this?

We add the presentations to our group library in zotero and then export it from there.

**Comment by kba** [comment]
Thanks, we'll integrate it.

The workflow for presentations/publications is to include them in our [Zotero group](http://zotero.org/groups/418719/ocr-d/) and export from there to generate the bibliographies.

**Comment by bertsky** [comment]
I see.

I know, most of the dev WS was module-specific. But this one just keeps getting raised, so people should be able to find (and reference) it.

**Comment by EEngl52** [comment]
Yes, I just added your presentation to the library
