### ISSUE TITLE
Where is ocrd_training?

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd-website#97]
IIUC the repos `docs` and `ocr-d.github.io` where integrated here.

Then I don't understand why there's no reference to https://github.com/OCR-D/ocr-d.github.io/blob/master/docs/ocrd-training.md anywhere on the website.

And is [this issue](https://github.com/OCR-D/ocr-d.github.io/issues/22) in the right repo?

**Comment by EEngl52** [comment]
I guess this issue is dublicating https://github.com/OCR-D/ocrd-website/issues/101? So we can close this one @bertsky ?

**Comment by bertsky** [comment]
I wouldn't strictly call it a duplicate. But yes, if the intention is to re-introduce the training notes, which #101 depends on, we can close here I guess.
